In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("marketmindz_research_data.csv")

In [4]:
print(df.shape)

(2240, 28)

In [5]:
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Response,Complain,Country
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,6,1,0,0,0,0,0,1,0,Spain
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,5,0,0,0,0,1,1,0,Canada
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,5,2,0,0,0,0,0,0,0,USA
3,1386,1967,Graduation,Together,32474.0,1,1,5/11/2014,0,10,...,2,7,0,0,0,0,0,0,0,Australia
4,5371,1989,Graduation,Single,21474.0,1,0,4/8/2014,0,6,...,2,7,1,0,0,0,0,1,0,Spain

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4    Income              2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntBakedProds        2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Response             2240 non-null   int64
 26  Complain             2240 non-null   int64
 27  Country              2240 non-null   object
dtypes: float64(1), int64(23), object(4)
memory usage: 490.1+ KB

In [7]:
df.isna().sum().sort_values(ascending=False).head(20)

 Income                24
ID                      0
NumDealsPurchases       0
Complain                0
Response                0
AcceptedCmp2            0
AcceptedCmp1            0
AcceptedCmp5            0
AcceptedCmp4            0
AcceptedCmp3            0
NumWebVisitsMonth       0
NumStorePurchases       0
NumCatalogPurchases     0
NumWebPurchases         0
MntBakedProds           0
Year_Birth              0
MntSweetProducts        0
MntFishProducts         0
MntMeatProducts         0
MntFruits               0
dtype: int64

In [8]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
      .str.replace("-", "_")
)

df.columns

Index(['id', 'year_birth', 'education', 'marital_status', 'income', 'kidhome',
       'teenhome', 'dt_customer', 'recency', 'mntwines', 'mntfruits',
       'mntmeatproducts', 'mntfishproducts', 'mntsweetproducts',
       'mntbakedprods', 'numdealspurchases', 'numwebpurchases',
       'numcatalogpurchases', 'numstorepurchases', 'numwebvisitsmonth',
       'acceptedcmp3', 'acceptedcmp4', 'acceptedcmp5', 'acceptedcmp1',
       'acceptedcmp2', 'response', 'complain', 'country'],
      dtype='object')

In [10]:
[c for c in df.columns if "spend" in c or "amt" in c or "sales" in c or "mnt" in c]

['mntwines',
 'mntfruits',
 'mntmeatproducts',
 'mntfishproducts',
 'mntsweetproducts',
 'mntbakedprods']

In [11]:
spend_cols = ['mntwines',
 'mntfruits',
 'mntmeatproducts',
 'mntfishproducts',
 'mntsweetproducts',
 'mntbakedprods']
df["total_spend"] = df[spend_cols].sum(axis=1)

In [12]:
df[['total_spend'] + spend_cols].head()

,total_spend,mntwines,mntfruits,mntmeatproducts,mntfishproducts,mntsweetproducts,mntbakedprods
0,1190,189,104,379,111,189,218
1,577,464,5,64,7,0,37
2,251,134,11,59,15,2,30
3,11,10,0,1,0,0,0
4,91,6,16,24,11,0,34

In [14]:
import os

os.makedirs("../data/processed", exist_ok=True)

In [15]:
df.to_csv("../data/processed/marketing_clean.csv", index=False)

In [16]:
import pandas as pd

pd.read_csv("../data/processed/marketing_clean.csv").head()

,id,year_birth,education,marital_status,income,kidhome,teenhome,dt_customer,recency,mntwines,...,numwebvisitsmonth,acceptedcmp3,acceptedcmp4,acceptedcmp5,acceptedcmp1,acceptedcmp2,response,complain,country,total_spend
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,1,0,0,0,0,0,1,0,Spain,1190
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,5,0,0,0,0,1,1,0,Canada,577
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,2,0,0,0,0,0,0,0,USA,251
3,1386,1967,Graduation,Together,32474.0,1,1,5/11/2014,0,10,...,7,0,0,0,0,0,0,0,Australia,11
4,5371,1989,Graduation,Single,21474.0,1,0,4/8/2014,0,6,...,7,1,0,0,0,0,1,0,Spain,91

In [17]:
import os
os.getcwd()

'C:\\Users\\jhj97\\MarketMinds'